import { mkdir, writeFile } from 'node:fs/promises'
import { join } from 'node:path'
import {
  ALL_MARKETS,
  MARKET_LABELS,
  marketProfile,
  type Market,
  type Product,
  type Store,
} from '@showing-up/shared'
import { detectPlatform, discoverPublicCatalogue, offeringFor, SHOPIFY_SELLABLE } from '@showing-up/connectors'
import {
  buildAcpFeed,
  buildMerchantFeed,
  buildUcpManifest,
  generateSigningKeyPair,
  policyGaps,
  toJsonl,
  validateUcpManifest,
} from '@showing-up/protocols'
import { runAudit, normaliseUrl, type AuditResult } from './audit.js'

/**
 * The delivery bundle: everything that lands with a customer, produced from a
 * store URL alone.
 *
 * This exists because "what do we actually deliver" was answerable only in
 * prose. It is answerable in files now: point it at a real storefront and it
 * writes the exact artefacts a paying merchant gets, hosted endpoints
 * included, plus the audit and the record.
 *
 * Nothing here is a mock. Every file is generated by the same code paths the
 * hosted app uses, so a defect in the sample is a defect in the product.
 */

export interface DeliverOptions {
  url: string
  market: Market
  outDir: string
  skuLimit?: number
  /** Skip the observation pass. Presence artefacts only, which needs no API keys. */
  presenceOnly?: boolean
  engines?: string
  repeats?: number
  onStage?: (message: string) => void
}

export interface DeliverResult {
  outDir: string
  store: Store
  products: Product[]
  offering: 'presence' | 'accuracy-only'
  files: { path: string; bytes: number; what: string }[]
  audit?: AuditResult
  notes: string[]
}

export async function deliver(options: DeliverOptions): Promise<DeliverResult> {
  const { url, market, outDir, skuLimit = 20, onStage = () => {} } = options
  const profile = marketProfile(market)
  const origin = normaliseUrl(url)
  const domain = new URL(origin).hostname.replace(/^www\./, '')
  const storeId = domain
  const notes: string[] = []
  const files: DeliverResult['files'] = []

  await mkdir(outDir, { recursive: true })
  const write = async (name: string, body: string | Uint8Array, what: string) => {
    const path = join(outDir, name)
    await mkdir(join(path, '..'), { recursive: true })
    await writeFile(path, body)
    files.push({ path: name, bytes: typeof body === 'string' ? Buffer.byteLength(body) : body.byteLength, what })
  }

  onStage(`detecting the platform behind ${domain}`)
  const detection = await detectPlatform(origin)
  const offering = offeringFor(detection.platform)
  notes.push(`platform detected as ${detection.platform} at ${Math.round(detection.confidence * 100)}% confidence`)
  notes.push(`offering for this platform: ${offering}`)
  if (offering === 'accuracy-only') {
    notes.push('Shopify store, so no presence hosting is generated or sold. Only these are on offer:')
    notes.push(...SHOPIFY_SELLABLE.map((line) => `  - ${line}`))
  }

  onStage('reading the public catalogue')
  const discovered = await discoverPublicCatalogue(origin, { limit: skuLimit })
  notes.push(`catalogue discovery: ${discovered.method}, confidence ${discovered.confidence}, ${discovered.products.length} products`)
  notes.push(...discovered.warnings)

  const store: Store = {
    id: storeId,
    domain,
    url: origin,
    platform: detection.platform,
    market,
    language: profile.language,
    connectorStatus: discovered.products.length ? 'feed' : 'none',
  }

  // -------------------------------------------------- job 1, presence
  // Not generated for a Shopify store. Shopify publishes its own merchants
  // and does it well; generating a competing manifest would be selling them
  // something they already have.
  if (offering === 'presence' && discovered.products.length) {
    onStage('building the presence artefacts')

    // Endpoints are written as they would be hosted on the merchant's own
    // domain, so the bundle is the real thing rather than a preview of it.
    const acpFeedUrl = `https://${domain}/feeds/acp.jsonl`

    // The hosted service issues the merchant an ES256 key pair. Only the
    // public half goes in the manifest, and the private half is never written
    // anywhere in this bundle: a delivery sample that shipped a private key
    // would be a delivery sample that leaked one.
    const keyPair = generateSigningKeyPair()
    const manifest = buildUcpManifest({ store, acpFeedUrl, signingKeys: [keyPair.publicJwk] })
    const validation = validateUcpManifest(manifest)
    await write('presence/.well-known/ucp', JSON.stringify(manifest, null, 2), 'UCP manifest, served at /.well-known/ucp on the merchant domain')
    const warningCount = validation.issues.filter((issue) => issue.severity === 'warning').length
    notes.push(`UCP manifest valid: ${validation.valid}${warningCount ? `, ${warningCount} warnings` : ''}`)
    notes.push(`signing key ${keyPair.publicJwk.kid} issued. The private half stays in the hosted key store and is not in this bundle.`)

    const feed = buildAcpFeed(discovered.products)
    await write('presence/feeds/acp.jsonl', toJsonl(feed.items), 'ACP product feed, the file ChatGPT, Perplexity and Claude read')
    await write(
      'presence/feeds/acp-exclusions.json',
      JSON.stringify(feed.exclusions, null, 2),
      'every product that did not reach the feed, each with the reason it was held back',
    )
    notes.push(`ACP feed: ${feed.items.length} of ${discovered.products.length} products, ${feed.exclusions.length} excluded with reasons`)

    await write(
      'presence/feeds/gmc.xml',
      buildMerchantFeed(discovered.products, { kind: 'google', title: store.domain, link: store.url }),
      'Google Merchant Center supplementary feed, for Gemini and AI Mode eligibility',
    )
    await write(
      'presence/feeds/mmc.xml',
      buildMerchantFeed(discovered.products, { kind: 'microsoft', title: store.domain, link: store.url }),
      'Microsoft Merchant Center feed, for Copilot eligibility',
    )

    const gaps = policyGaps(undefined, { market })
    await write(
      'presence/policies-required.json',
      JSON.stringify({ market, marketRules: profile, gaps }, null, 2),
      'the policy fields this market requires, and what an agent cannot answer without each one',
    )
    notes.push(`policy gaps for ${MARKET_LABELS[market]}: ${gaps.length} (${gaps.filter((g) => g.severity === 'blocker').length} blocking)`)
  }

  // -------------------------------------------------- jobs 2 and 3
  let audit: AuditResult | undefined
  if (!options.presenceOnly && discovered.products.length) {
    onStage('observing the surfaces and diffing against the catalogue')
    try {
      audit = await runAudit({
        url: origin,
        market,
        language: profile.language,
        engines: (options.engines ?? 'api') as never,
        repeats: options.repeats ?? 2,
        skuLimit,
        queryCount: 20,
        outRoot: join(outDir, 'audit'),
        panelDir: 'panel',
        inferCause: false,
        priceTolerance: 0.01,
        onStage: (message) => onStage(`  ${message}`),
      } as Parameters<typeof runAudit>[0])
    } catch (error) {
      notes.push(`observation pass did not run: ${error instanceof Error ? error.message : String(error)}`)
    }
  }

  await write('DELIVERY.md', readme({ store, offering, discovered, files, notes, audit }), 'what each file in this bundle is')
  return { outDir, store, products: discovered.products, offering, files, notes, ...(audit ? { audit } : {}) }
}

function readme(input: {
  store: Store
  offering: 'presence' | 'accuracy-only'
  discovered: { method: string; confidence: string; products: Product[] }
  files: { path: string; what: string }[]
  notes: string[]
  audit?: AuditResult
}): string {
  const { store, offering, discovered, files, notes } = input
  const profile = marketProfile(store.market)
  return `# Delivery bundle: ${store.domain}

Generated ${new Date().toISOString()} by the Showing Up harness from the store URL alone.
No credentials were used. Every file here came from what the store already publishes.

- Store: ${store.url}
- Platform: ${store.platform}
- Market: ${MARKET_LABELS[store.market]} (${profile.currency}, ${profile.locale}, ${profile.taxLabel} ${profile.taxMode})
- Offering: ${offering}
- Catalogue read by: ${discovered.method}, confidence ${discovered.confidence}, ${discovered.products.length} products

## Files

${files.map((file) => `- \`${file.path}\`\n  ${file.what}`).join('\n')}

## Run notes

${notes.map((note) => `- ${note}`).join('\n')}

## What is deliberately absent

${
  offering === 'accuracy-only'
    ? `This is a Shopify store, so no presence artefacts were generated. Shopify already
publishes its merchants to the AI surfaces and reports which category queries they
rank for. We sell a Shopify merchant three things only:

${SHOPIFY_SELLABLE.map((line) => `- ${line}`).join('\n')}`
    : `Nothing. This platform gets the full presence set plus the audit.`
}

Every observation in the audit carries the method it was made by. A surface below the
0.8 reproducibility floor is reported as not observable and raises no findings, rather
than being approximated from another surface.
`
}

/** The markets the deliver command accepts, for the CLI help text. */
export const DELIVERABLE_MARKETS = ALL_MARKETS
